template_path: packer-ami-pipeline.yaml
parameters:
  RepositoryName: "polarseven/packer-ami-pipeline"
  RepositoryDescription: "AMI Builder repository stuff." 
  PipelineName: "{{stack_group_config.Owner}}_ami-builder"
  RepositoryBranch: "master"
  ProjectName: "{{stack_group_config.Owner}}_CodeBuild"
  CodeBuildImage: "aws/codebuild/ubuntu-base:14.04"