template_path: packer-ami-pipeline.yaml
parameters:
  RepositoryName: "packer-ami-pipeline"
  RepositoryOwner: "davidtpwilliams"
  RepositoryDescription: "AMI Builder repository stuff." 
  PipelineName: "{{stack_group_config.Owner}}_ami-builder"
  OAuthToken: "762fed7c92f0c2100b8cf2df7a43a12d4674f29f"
  RepositoryBranch: "master"
  ProjectName: "{{stack_group_config.Owner}}_CodeBuild"
  CodeBuildImage: "aws/codebuild/ubuntu-base:14.04"